packages/@lwc/jest-transformer/src/index.js
packages/@lwc/jest-transformer/src/test/modules/example/messageChannel/__tests__/messageChannel.test.js
packages/@lwc/jest-transformer/src/test/modules/example/messageChannel/messageChannel.html
packages/@lwc/jest-transformer/src/test/modules/example/messageChannel/messageChannel.js
packages/@lwc/jest-transformer/src/transforms/__tests__/message-channel-scoped-import.test.js
packages/@lwc/jest-transformer/src/transforms/message-channel-scoped-import.js

Jest transformer support for the `@salesforce/messageChannel` import type.

feat: support @salesforce/messageChannel

---

packages/@lwc/jest-preset/jest-preset.js
packages/@lwc/jest-transformer/package.json
packages/@lwc/jest-transformer/src/index.js

This PR adds the necessary changes to pre-transform TypeScript files (see #35).
It fixes the issue opened here:
https://github.com/muenzpraeger/create-lwc-app/issues/92

Adding TypeScript support for LWC OSS

---

packages/@lwc/jest-serializer/src/__tests__/__snapshots__/clean-element-attrs.spec.js.snap
packages/@lwc/jest-serializer/src/__tests__/clean-element-attrs.spec.js
packages/@lwc/jest-serializer/src/clean-element-attrs.js

Removing attributes completely is likely to cause confusion so it's better to leave a placeholder that indicates that we are doing something there.

refactor(serializer): replace attributes with placeholders instead of removing

---

package.json
packages/@lwc/jest-preset/jest-preset.js
packages/@lwc/jest-preset/package.json
scripts/jest/base.config.js
yarn.lock

Moving back to the original way we pulled in jsdom@15 since the maintainer recently upgraded the jsdom subdep. This makes it so that it doesn't matter whether the user uses npm or yarn to install @lwc/jest-preset.

build(jest-preset): refactor jsdom resolution

---

package.json
packages/@lwc/jest-preset/jest-preset.js
packages/@lwc/jest-preset/package.json
packages/@lwc/jest-transformer/package.json
scripts/jest/base.config.js
yarn.lock

- test: pulls in the latest version of `jsdom` via `jest-environment-jsdom-fifteen`.
- build: removes peer dependencies where applicable for dependencies distributed under the `lwc` package to support consumption via both sub and direct dependency.

build: jsdom@15.2.1 via jest-environment-jsdom-fifteen

---

yarn.lock

Lerna commands were throwing the error:
`Error: Cannot find module 'npm-normalize-package-bin'`
Reinstalling lerna fixed the problem.

build: fix lerna dependencies

---

packages/@lwc/jest-preset/package.json
packages/@lwc/jest-transformer/package.json

Users currently have two ways of consuming the @lwc packages distributed by the lwc dist package so having peer dependencies causes issues. Removing them for now until we have a better story around managing dependencies.

build: remove peer dependencies (for now)

---

package.json
packages/@lwc/jest-preset/package.json
packages/@lwc/jest-resolver/package.json
packages/@lwc/jest-resolver/src/index.js
packages/@lwc/jest-transformer/package.json
packages/@lwc/jest-transformer/src/index.js
yarn.lock

Looks like I screwed up some of the dependencies while working in `lwc-test`. This PR fixes those and also fixes some existing dependency misconfigurations.

build: fix incorrect dependencies

---

packages/@lwc/jest-transformer/src/index.js
packages/@lwc/jest-transformer/src/test/modules/example/dynamicImport/__tests__/__snapshots__/dynamicImport.test.js.snap
packages/@lwc/jest-transformer/src/test/modules/example/dynamicImport/__tests__/dynamicImport.test.js
packages/@lwc/jest-transformer/src/test/modules/example/dynamicImport/dynamicImport.html
packages/@lwc/jest-transformer/src/test/modules/example/dynamicImport/dynamicImport.js

[babelDynamicImport](https://github.com/salesforce/lwc-test/blob/master/packages/%40lwc/jest-transformer/src/index.js#L37) will take care of correctly transform the import. But the default option of the lwc compiler is `strictSpecifier: true`, making invalid the import syntax when used with an identifier.
This PR lift that restriction on jest environments.

fix: support dynamic imports in jest tests

---

packages/@lwc/jest-preset/jest-preset.js
packages/@lwc/jest-preset/src/stubs/__tests__/instrumentationServiceStub.test.js

Clients use the instrumentation service via:
`import * as metricsService from "instrumentation/service";`
The existing moduleNameMapper failed to resolve this import and mock the service. 
Testing using the existing moduleNameMapper fails to resolve the stub:
>  FAIL  __tests__/instrumentation.test.js
>  ● Test suite failed to run
>
>    Cannot find module 'instrumentation/service' from 'instrumentation.js'
>
>       5 |  */
>       6 | 
>       7 | import * as metricsService from "instrumentation/service";
A check of core found no relevant uses of the existing moduleNameMapper:
`~/blt/app/main/core$ grep -R instrumentation-service *
......./InstrumentationServiceImpl.java:            brave.Span childSpan = zipkinTracer.nextSpan().name("instrumentation-service");
~/blt/app/main/core$` …

fix for correct import of instrumentation/service

---

package.json
packages/@lwc/jest-preset/src/__tests__/changeRuntimeValidWireAdapters.spec.js
packages/@lwc/jest-preset/src/__tests__/mockedInvalidWireAdapters.spec.js
packages/@lwc/jest-preset/src/__tests__/nonMockedValidWireAdapters.spec.js
packages/@lwc/jest-preset/src/__tests__/simpleComponent.spec.js
packages/@lwc/jest-preset/src/__tests__/utils.js
packages/@lwc/jest-preset/src/setup.js
packages/@lwc/jest-preset/src/test/modules/example/adapter/adapter.js
packages/@lwc/jest-preset/src/test/modules/example/simpleComponent/simpleComponent.html
packages/@lwc/jest-preset/src/test/modules/example/simpleComponent/simpleComponent.js
packages/@lwc/jest-preset/src/test/modules/example/wiredComponent/wiredComponent.html
packages/@lwc/jest-preset/src/test/modules/example/wiredComponent/wiredComponent.js
yarn.lock

With the [Wire protocol reform](https://github.com/salesforce/lwc-rfcs/blob/master/text/0000-wire-reform.md), the wire-service now requires a wire-adapter (even a mock) in the proper format, otherwise the test of a component using a wire will throw during rendering.
This PR hijacks the decorators registration system of the engine to replace the used wire-adapter (maybe invalid) with a valid one.

chore: upgrade to lwc version 1.5.0

---

packages/@lwc/jest-preset/src/__tests__/componentWithMixin.spec.js
packages/@lwc/jest-preset/src/setup.js
packages/@lwc/jest-preset/src/test/modules/example/componentWithMixin/componentWithMixin.html
packages/@lwc/jest-preset/src/test/modules/example/componentWithMixin/componentWithMixin.js
packages/@lwc/jest-preset/src/test/modules/example/wiredComponent/wiredComponent.js

Fixes an issue with the `registerDecorator` proxy, that does not returns the result from calling the original `lwc.registerDecorator`

fix(jest-preset): registerDecorators proxy does not returns original call result

---

package.json
yarn.lock

Our dependency tree no longer contains the problematic modules that these entries addressed.

build: remove yarn resolutions entries

---

packages/@lwc/jest-preset/package.json
packages/@lwc/jest-resolver/package.json
packages/@lwc/jest-serializer/package.json
packages/@lwc/jest-transformer/package.json

This is important because it improves the UX on npmjs.org with a link
back to the git repository.

docs: add homepage link in each project package.json

---

packages/@lwc/jest-transformer/src/index.js

Fixes potential conflict with babel configs upstream

fix: ignore babelrc for typescript

---

packages/@lwc/jest-preset/package.json
packages/@lwc/jest-resolver/package.json
packages/@lwc/jest-serializer/package.json
packages/@lwc/jest-transformer/package.json

We still need to make sure that `jest` is at least v25.5.4 to avoid the `@jest/globals` issue.

chore: relax jest peer dependency

---

.eslintignore

- Removes non-existant directories from `.eslintignore`.

chore: Remove wdio eslint artifact

---

packages/@lwc/jest-preset/jest-preset.js

Remove `testURL` from `jest.preset.js`. This has been merged with Jest 25.

chore: cleanup testURL

---

packages/@lwc/jest-preset/package.json
packages/@lwc/jest-resolver/package.json
packages/@lwc/jest-serializer/package.json
packages/@lwc/jest-transformer/package.json
packages/@lwc/jest-transformer/src/index.js
yarn.lock

- Update all the `peerDependencies` to match
- Update all the dependencies versions and move to a `^` version pinning (more details on this below)
- Remove unused packages: `babel-plugin-transform-dynamic-import`, `@babel/template`
- Normalize `license`, `keywords` and `main` fields between projects
**Why moving to `^` versioning pinning?** 
Historically, we decided that using `~` was the safest approach to version dependencies for LWC related projects to prevent unexpected downstream breaking changes. I do think that this project doesn't need to follow the same semantic:
- Jest uses `^` to pin [dependencies](https://github.com/facebook/jest/blob/v26.6.3/packages/jest-cli/package.json) (regardless if the dependency is external to jest or not). Because of this, even if we protect this …

chore: Project dependencies update

---

packages/@lwc/jest-preset/package.json

`@lwc/engine` is not marked as a peer dependency of `@lwc/jest-preset`. However, `@lwc/engine` is required during the [environment setup](https://github.com/salesforce/lwc-test/blob/master/packages/%40lwc/jest-preset/src/setup.js#L149).

fix: add @lwc/engine as peerDependency of @lwc/jest-preset

---

packages/@lwc/jest-preset/package.json
test/package.json

I made a mistake during the v11.0.0 update, so I skipped some dependency versions, causing tests to fail.

fix: update dep versions

---

CONTRIBUTING.md

These release steps are incorrect (`yarn release` does not work), and I'm putting the full release steps in another document anyway: https://salesforce.quip.com/5tk3Ab98Dl8B

docs: remove release steps

---

.circleci/config.yml
.eslintrc
package.json
packages/@lwc/jest-preset/jest-preset.js
packages/@lwc/jest-preset/package.json
packages/@lwc/jest-resolver/package.json
packages/@lwc/jest-serializer/package.json
packages/@lwc/jest-transformer/package.json
packages/@lwc/jest-transformer/src/index.js
yarn.lock

- Update project dependencies
- Update `peerDependencies` field to include both `jest@26` and `jest@27`
- Add matrix test to CircleCI to check supported version

feat: Add support for jest@27

---

packages/@lwc/jest-preset/src/setup.js

This adds an explicit error if we detect that `@lwc/synthetic-shadow` has been loaded twice by Jest. This would have saved me hours of debugging, so maybe it will save some time for the next person.
For the life of me, I can't figure out how to actually reproduce this in this repo. Even if I manually set `jest` and `jsdom` to exactly the versions in the other repo, I can't repro. However, I can at least confirm that, in the other repo, I can hit this line of code in their tests:
W-9786068

fix: warn if synthetic shadow is loaded twice

---

test/src/modules/resolver/manualStylesheets/__tests__/manualStylesheets.test.js
test/src/modules/resolver/manualStylesheets/manualStylesheets.css
test/src/modules/resolver/manualStylesheets/manualStylesheets.html
test/src/modules/resolver/manualStylesheets/manualStylesheets.js

Manually setting the stylesheets on the template is not a supported scenario, but it happens to work:
```js
import template from './cmp.html'
import stylesheet from './cmp.css'
export default class extends LightningElement {
render() {
template.stylesheets = [stylesheet]
return template
}
}
```
(Note this works even if `stylesheet` is already an array, because the LWC runtime engine deeply recurses arrays of stylesheet functions.)
That is, it works in the browser using the standard `@lwc/rollup-plugin`, but it doesn't work in Jest. It throws an error:
```
TypeError: Cannot read property '$scoped$' of undefined
at computeHasScopedStyles
```
This PR fixes that.
W-10686573

fix: fix manually setting template.stylesheets

---

.circleci/config.yml
package.json
packages/@lwc/jest-preset/README.md
packages/@lwc/jest-preset/package.json
packages/@lwc/jest-preset/src/setup.js
packages/@lwc/jest-resolver/package.json
packages/@lwc/jest-resolver/src/index.js
packages/@lwc/jest-serializer/package.json
packages/@lwc/jest-transformer/package.json
yarn.lock

This PR adds support for Jest@28. 
One major callout. With version 28, Jest stopped shipping `jest-environment-jsdom` by default ([post](https://jestjs.io/blog/2022/04/25/jest-28#jsdom-19)). Consumers are now required to install this package separately. I don't think it's worth a major version bump, but it's something we should call out in the release note.

Add support for Jest@28

---

packages/@lwc/jest-preset/src/ssr/resolver.js
packages/@lwc/jest-resolver/src/index.js
test/src/modules/resolver/basic/__tests__/basic.test.js
test/src/modules/resolver/scopedCss/__tests__/scopedCss.test.js
test/src/modules/resolver/scopedCss/basic.html
test/src/modules/resolver/scopedCss/basic.js
test/src/modules/resolver/scopedCss/basic.scoped.css

Currently, we only render CSS in server mode, not client mode. We should really render the CSS in both cases.
This moves the CSS rendering logic from `@lwc/jest-preset/src/ssr/resolver.js` to `@lwc/jest-resolver/src/index.js` and makes both the client and server resolver rely on the same logic.

fix: render CSS correctly on both client and server

---

packages/@lwc/jest-transformer/src/index.js

Note: These feature are still meant for internal usage and that is enforced at the compiler level. This PR only adds support for those feature when testing the components.

feat(jest-transformer): enable scoped slots and lwc:spread feature by default for testing

---

packages/@lwc/jest-serializer/README.md

We were missing the `@lwc` here.

docs: fix typo in README

---

packages/@lwc/jest-resolver/src/index.js
packages/@lwc/jest-shared/README.md
packages/@lwc/jest-shared/package.json
packages/@lwc/jest-shared/src/index.js
packages/@lwc/jest-transformer/package.json
packages/@lwc/jest-transformer/src/index.js

Currently `lwc-test` is the only case where we use `.scoped.css` in the filename as a signal for whether a CSS file is scoped or not. Technically we should be using the presence of `?scoped=true`.
In Jest, I could not figure out a way to plumb the query param through from the resolver to the transformer. Research on how to do this turned up nothing.
The simplest solution I could find is to create a new package, `@lwc/jest-shared`, which serves as a communication mechanism between `@lwc/jest-resolver` and `@lwc/jest-transformer`. One notes the presence of `?scoped=true`, whereas the other looks up a filename later to see if it should be treated as scoped.

fix: use ?scoped=true as signal for scoped CSS

---

test/src/modules/resolver/manualStylesheets/__tests__/manualStylesheets.test.js

This disables an annoying error message in our tests:
<details><summary>Click to see</summary>
```
● Console                                                                                                                           
console.error                                                                                                                     
[LWC error]: Dynamically setting the "stylesheets" property on a template function is deprecated and may be removed in a future version of LWC.
809 |     if (process.env.NODE_ENV === 'test') {                                                                                
810 |         /* eslint-disable-next-line no-console */                                                                         
> 811 | …
```

chore: ignore expected console.error message

---

packages/@lwc/jest-transformer/src/index.js
test/src/modules/smoke/dynamicCmp/__tests__/__snapshots__/dynamicCmp.test.js.snap
test/src/modules/smoke/dynamicCmp/__tests__/dynamicCmp.test.js
test/src/modules/smoke/dynamicCmp/dynamicCmp.html
test/src/modules/smoke/dynamicCmp/dynamicCmp.js

This PR enables [dynamic components](https://github.com/salesforce/lwc-rfcs/blob/master/text/0133-dynamic-component-creation.md) for testing.
This PR only enables dynamic components, a follow-up PR will be needed to retrieve the namespace and name to properly create a dynamic component with the correct tag name which is a breaking change.
In 244, the users of dynamic components are internal developers and a pilot group of ISVs.

feat(jest-transformer): enable new dynamic components

---

packages/@lwc/jest-preset/src/setup.js

In https://github.com/salesforce/lwc/pull/3456 I plan to move the location of the `dist/` file for `@lwc/synthetic-shadow`. We are directly depending on the current location:
https://github.com/salesforce/lwc-test/blob/69fdc0c8ed1fe3522fab01049b305cf5b5b2d0f1/packages/%40lwc/jest-preset/src/setup.js#L15
This PR future-proofs us, so that we work with either the old or new location.

fix: future-proof against changes to synthetic shadow

---

packages/@lwc/jest-preset/src/setup.js

Now that we bumped the minimum required LWC version (#185), there is no need for a fallback synthetic shadow import anymore (added in #179). We can safely remove this code.

chore: remove fallback synthetic shadow import (BREAKING CHANGE)

---

packages/@lwc/jest-preset/src/ssr/html-serializer.js
packages/@lwc/jest-serializer/src/clean-style-element.js
packages/@lwc/jest-shared/src/index.js
test/src/modules/ssr/scopedStyle/__tests__/scopedStyle.ssr-test.js

This was an oversight in #185. I missed doing this for SSR snapshots.
Arguably this is a breaking change, but I'm going to consider it a bugfix because it should have been done in v12.0.0.

fix(ssr): replace scope token in SSR serializer

---

packages/@lwc/jest-preset/src/setup.js

I missed this in #186. I removed the wrong import. 🤦

fix: remove synthetic shadow fallback import for real

---

packages/@lwc/jest-shared/src/index.js
test/src/modules/ssr/scopedStyle/__tests__/scopedStyle.ssr-test.js
test/src/modules/ssr/scopedStyleHostLight/__tests__/scopedStyleHostLight.ssr-test.js
test/src/modules/ssr/scopedStyleHostLight/scopedStyleHostLight.html
test/src/modules/ssr/scopedStyleHostLight/scopedStyleHostLight.js
test/src/modules/ssr/scopedStyleHostLight/scopedStyleHostLight.scoped.css

Another thing missed in #187. We need to sort the regex input so that the full `foo-host` string is replaced.

fix(serializer): remove "-host" from serialized scope token

---

packages/@lwc/jest-serializer/src/clean-element-attrs.js
packages/@lwc/jest-shared/src/index.js
test/src/modules/serializer/errors/__tests__/__snapshots__/errors.spec.js.snap
test/src/modules/serializer/errors/__tests__/errors.spec.js
test/src/modules/serializer/errors/errors.html
test/src/modules/serializer/errors/errors.js
test/src/modules/serializer/errors2/__tests__/__snapshots__/errors2.spec.js.snap
test/src/modules/serializer/errors2/__tests__/errors2.spec.js
test/src/modules/serializer/errors2/errors2.html
test/src/modules/serializer/errors2/errors2.js

Fixes some errors we've seen in the wild:
```
Cannot read properties of undefined (reading 'toLowerCase')TypeError: Cannot read properties of undefined (reading 'toLowerCase')
at isKnownScopeToken (node_modules/@lwc/jest-shared/src/index.js:38:37)
```
```
elm.attributes is not iterableTypeError: elm.attributes is not iterable
at cleanElementAttributes (node_modules/@lwc/jest-serializer/src/clean-element-attrs.js:47:16)
```
W-13672056

fix: fix serializer errors with elm.attributes

---

packages/@lwc/jest-transformer/package.json
packages/@lwc/jest-transformer/src/index.js

To prevent tons of warning log lines, the LWC compiler option `enableLwcSpread` is now only configured for compiler versions lower than 2.49.1.
The PR that lead to these log lines is https://github.com/salesforce/lwc/pull/3544 ([v2.49.1](https://github.com/salesforce/lwc/releases/tag/v2.49.1)).

fix: configure `enableLwcSpread` compiler option conditionally

---

packages/@lwc/jest-serializer/src/clean-element-text-content.js
packages/@lwc/jest-serializer/src/index.js
test/src/modules/serializer/emptyTextNode/__tests__/__snapshots__/emptyTextNode.spec.js.snap
test/src/modules/serializer/emptyTextNode/__tests__/emptyTextNode.spec.js
test/src/modules/serializer/emptyTextNode/emptyTextNode.html
test/src/modules/serializer/emptyTextNode/emptyTextNode.js

Breaking change, don't merge until we have the other breaking change in (which would address #198).
This makes snapshots resilient to empty text nodes, which fixes the extra whitespace caused by https://github.com/salesforce/lwc/pull/3308.
W-13831241

fix: make snapshots resilient to whitespace changes (BREAKING CHANGE)

---

packages/@lwc/jest-preset/package.json
packages/@lwc/jest-transformer/package.json

The `>=` format will allow us to avoid needing to change this when lwc v4.0.0 is released.

fix: improve peerDep for lwc

---

packages/@lwc/jest-serializer/src/clean-element-text-content.js

In `ui-help-components`, for some reason the line
```js
node.removeChild(child)
```
... fails with the error
```js
PrettyFormatPluginError: The node to be removed is not a child of this node.
NotFoundError: The node to be removed is not a child of this node.
```
I debugged, and the error comes from JSDOM [here](https://github.com/jsdom/jsdom/blob/a39e0ec4ce9a8806692d986a7ed0cd565ec7498a/lib/jsdom/living/nodes/Node-impl.js#L1059-L1064). And it's bizarre, because `child.parentNode === node` and `node.childNodes[0] === child`, so one is definitely a child of the other.
In any case, changing this to `child.remove()` fixes the error. 🤷

fix: fix error with removing child node

---

packages/@lwc/jest-preset/src/ssr/html-serializer.js
test/src/modules/ssr/emptyTextExpression/__tests__/__snapshots__/emptyTextExpression.ssr-test.js.snap
test/src/modules/ssr/emptyTextExpression/__tests__/emptyTextExpression.ssr-test.js
test/src/modules/ssr/emptyTextExpression/emptyTextExpression.html
test/src/modules/ssr/emptyTextExpression/emptyTextExpression.js
test/src/modules/ssr/lightDomSlotElement/__tests__/__snapshots__/lightDomSlotElement.ssr-test.js.snap
test/src/modules/ssr/lightDomSlotElement/__tests__/lightDomSlotElement.ssr-test.js
test/src/modules/ssr/lightDomSlotElement/lightDomSlotElement.html
test/src/modules/ssr/lightDomSlotElement/lightDomSlotElement.js
test/src/modules/ssr/lightDomSlotEmpty/__tests__/__snapshots__/lightDomSlotEmpty.ssr-test.js.snap
test/src/modules/ssr/lightDomSlotEmpty/__tests__/lightDomSlotEmpty.ssr-test.js
test/src/modules/ssr/lightDomSlotEmpty/lightDomSlotEmpty.html
test/src/modules/ssr/lightDomSlotEmpty/lightDomSlotEmpty.js
test/src/modules/ssr/lightDomSlotText/__tests__/__snapshots__/lightDomSlotText.ssr-test.js.snap
test/src/modules/ssr/lightDomSlotText/__tests__/lightDomSlotText.ssr-test.js
test/src/modules/ssr/lightDomSlotText/lightDomSlotText.html
test/src/modules/ssr/lightDomSlotText/lightDomSlotText.js
test/src/modules/ssr/lightDomSlottable/lightDomSlottable.html
test/src/modules/ssr/lightDomSlottable/lightDomSlottable.js

BREAKING CHANGE: snapshots must be updated
Fixes #204
Replaces all ZWJ characters before serializing SSR snapshots. This deals with how empty text nodes are serialized in SSR (see https://github.com/salesforce/lwc/pull/2656).
Some of these tests won't actually have an observable difference until https://github.com/salesforce/lwc/pull/3649 is merged. You'll just have to take my word for it that the snapshots are the same before and after that change. (I tested manually.)

fix(ssr): do not serialize ZWJ characters

---

packages/@lwc/jest-preset/src/aria-reflection-polyfill.js
test/src/modules/smoke/aria/__tests__/aria.spec.js

This was an oversight from #207. In both the [LWC polyfill](https://github.com/salesforce/lwc/blob/44a01efb1ad9210b780c6d7094994ad24652f181/packages/%40lwc/aria-reflection/src/polyfill.ts#L25-L26) and in Safari/Chrome, these props are enumerable/configurable. Without that, you can't override them, which might break other polyfills.

fix: aria props should be configurable/enumerable

---

packages/@lwc/jest-preset/README.md
packages/@lwc/jest-preset/package.json
packages/@lwc/jest-preset/src/matchers/expect-throw-in-connected-callback.js
packages/@lwc/jest-preset/src/setup.js
packages/@lwc/jest-preset/types/index.d.ts
test/src/modules/smoke/matchers/__tests__/matchers.test.js
test/src/modules/smoke/matchers/matchers.js

After running the Jest tests in core, I realized that a lot of component authors are doing something like this:
```js
expect(() => {
document.body.appendChild(createComponent()) // throws in connectedCallback
}).toThrow('foo')
```
This doesn't work with native custom element lifecycle, because the error is no longer thrown locally, as described  in https://github.com/salesforce/lwc/pull/3662.
I believe component authors need a simple way to assert on errors thrown in `connectedCallback`s. So I propose adding a new matcher:
```js
expect(() => {
...
}).toThrowInConnectedCallback('foo')
```
This PR adds this new matcher. This matcher works both with LWC components and with native custom elements. It doesn't matter whether the LWC components are running in native lifecycle mode or synthetic …

feat: add `expect().toThrowInConnectedCallback` matcher

---

packages/@lwc/jest-transformer/src/index.js
packages/@lwc/jest-transformer/src/transforms/__tests__/import-meta.test.js
packages/@lwc/jest-transformer/src/transforms/import-meta.js

This PR adds support for `import.meta` properties inside components that are unit tested via Jest. To do so `import.meta.*` properties are rewritten to `process.*`. Special treatment is added for boolean `import.meta.env.*` properties due to the fact that `process.env.*` only allows/supports string properties.

feat: add support for `import.meta` properties @W-14387292

---

packages/@lwc/jest-transformer/src/transforms/__tests__/import-meta.test.js
packages/@lwc/jest-transformer/src/transforms/import-meta.js

Fixes #221.
Instead of replacing every `MetaProperty` with `process`, we check first if it is an `import.meta` meta property. This avoids replacing `new.target`.

fix(jest-transformer): do not replace new.target

---

packages/@lwc/jest-serializer/src/clean-element-styles.js
test/src/modules/serializer/styleAttr/__tests__/__snapshots__/styleAttr.spec.js.snap
test/src/modules/serializer/styleAttr/styleAttr.html
test/src/modules/serializer/styleAttr/styleAttr.js

It occurred to me that, instead of regexes, we can use the `elm.style` CSSStyleDeclaration object to serialize out the `style` attribute. This has some benefits:
1. We delegate the hard work to JSDOM
2. We can handle stuff like `data:` base64 URLs correctly
And some downsides:
1. JSDOM's parsing does not seem perfect, e.g. it doesn't seem to understand `! important` (due to the space) and it doesn't seem to like a leading `;`
2. For invalid CSS declarations (e.g. `color: yolo`) it will just strip them out
3. JSDOM normalizes some values, e.g. `background-color:#FFFFFF;"` becomes `background-color: rgb(255, 255, 255);`
I think this is an acceptable tradeoff, especially since it makes the code a lot cleaner.

fix: use jsdom to parse style attr and serialize it

---

packages/@lwc/jest-serializer/src/clean-element-attrs.js
packages/@lwc/jest-serializer/src/clean-element-styles.js
packages/@lwc/jest-serializer/src/index.js
test/src/modules/serializer/styleAttr/__tests__/__snapshots__/styleAttr.spec.js.snap
test/src/modules/serializer/styleAttr/__tests__/styleAttr.spec.js
test/src/modules/serializer/styleAttr/styleAttr.html
test/src/modules/serializer/styleAttr/styleAttr.js

Split into two commits to make the changes more obvious.
See #236 for class changes.
BREAKING CHANGE: snapshots may change.
W-15365974

fix(serializer): normalize style attributes

---

test/src/modules/serializer/styleAttr/__tests__/styleAttr.spec.js
test/src/modules/transformer/apex/__tests__/apex.test.js

This removes an annoying error message in the test (which is totally expected) and also improves the tests for apex methods returning a promise.

test: ignore expected console error and improve test

---

packages/@lwc/jest-preset/src/ssr/html-serializer.js
test/src/modules/serializer/frameworkAttrsWithValue/__tests__/__snapshots__/frameworkAttrsWithValue.spec.js.snap
test/src/modules/serializer/frameworkAttrsWithValue/__tests__/frameworkAttrsWithValue.spec.js
test/src/modules/serializer/frameworkAttrsWithValue/frameworkAttrsWithValue.css
test/src/modules/serializer/frameworkAttrsWithValue/frameworkAttrsWithValue.html
test/src/modules/serializer/frameworkAttrsWithValue/frameworkAttrsWithValue.js
test/src/modules/ssr/frameworkAttrsWithValue/__tests__/__snapshots__/frameworkAttrsWithValue.ssr-test.js.snap
test/src/modules/ssr/frameworkAttrsWithValue/__tests__/frameworkAttrsWithValue.ssr-test.js
test/src/modules/ssr/frameworkAttrsWithValue/frameworkAttrsWithValue.css
test/src/modules/ssr/frameworkAttrsWithValue/frameworkAttrsWithValue.html
test/src/modules/ssr/frameworkAttrsWithValue/frameworkAttrsWithValue.js

Due to https://github.com/salesforce/lwc/pull/4385, we now need to trim the attribute value as well as the attribute name for `data-lwc-host-mutated`.

fix: trim `data-lwc-host-mutated` attr values

---

packages/@lwc/jest-preset/README.md
packages/@lwc/jest-transformer/src/transforms/__tests__/apex-continuation-scoped-import.test.js
packages/@lwc/jest-transformer/src/transforms/__tests__/apex-scoped-import.test.js
packages/@lwc/jest-transformer/src/transforms/utils.js
test/src/modules/transformer/apex/__tests__/apex.test.js

After looking for ways to  simplify mocking apex methods in a SFDX project, I found this transformer is applied. However the apex method transforms don't make the imports available within jests. 
This change allows for jests import and use apex methods cleanly without having to mock in each test file. 
This doesn't apply to wired apex methods which would need `createApexTestWireAdapter()`  from [@salesforce/sf](https://github.com/salesforce/sfdx-lwc-jest)
```js
// foo.test.js
import apexMethod from "@salesforce/apex/ApexClass.apexMethod";
describe("c-foo", () => {
afterEach(() => {
// resetEnvironment();
});
it("Test mock", async () => {
apexMethod.mockResolvedValue('value');
}
}
```
Otherwise any apex method requires
```js 
jest.mock(
"@salesforce/apex/ApexClass.apexMethod",
() => { …
```

Update @salesforce/apex/* imports to return jest.fn()

---

packages/@lwc/jest-preset/src/ssr/html-serializer.js
packages/@lwc/jest-serializer/src/clean-element-attrs.js
test/src/modules/serializer/frameworkAttrsWithValue/frameworkAttrsWithValue.js
test/src/modules/ssr/frameworkAttrsWithValue/frameworkAttrsWithValue.js

We recently added a new framework-specific HTML attribute in https://github.com/salesforce/lwc/pull/4865. This should be ignored by the Jest snapshotter so that it doesn't pollute the snapshot output with attributes that component authors don't care about.

fix(snapshots): ignore `data-lwc-host-scope-token`
