salesforce/lwc-test

- packages/@lwc/jest-transformer/README.md
Providing a brief overview on Jest transformers and how this package uses them
> updated README to give an overview of the jest-transformer package

- packages/wdio-lwc-service/examples/basic/package.json
- packages/wdio-lwc-service/examples/basic/yarn.lock
CVE-2019-10744 
WS-2019-0032
WS-2019-0063
> address security alerts

- package.json
- yarn.lock
> build: lwc@1.1.13-224.3

- package.json
- packages/@lwc/jest-preset/package.json
- yarn.lock
https://github.com/salesforce/lwc-test/network/alert/yarn.lock/set-value/open
> build: bump versions to address security alert CVE-2019-10747

- package.json
- packages/@lwc/jest-preset/package.json
- packages/@lwc/jest-resolver/package.json
- packages/@lwc/jest-resolver/src/index.js
- packages/@lwc/jest-transformer/package.json
- packages/@lwc/jest-transformer/src/index.js
- yarn.lock
Same idea as https://github.com/salesforce/lwc-test/pull/57 but adds correct usage of @lwc/module-resolver.
> build: fix incorrect dependencies

- packages/@lwc/jest-transformer/src/index.js
- packages/@lwc/jest-transformer/src/test/modules/example/accessCheck/__tests__/__snapshots__/accessCheck.test.js.snap
- packages/@lwc/jest-transformer/src/test/modules/example/accessCheck/__tests__/accessCheck.test.js
- packages/@lwc/jest-transformer/src/test/modules/example/accessCheck/accessCheck.html
- packages/@lwc/jest-transformer/src/test/modules/example/accessCheck/accessCheck.js
- packages/@lwc/jest-transformer/src/transforms/__tests__/access-check-scoped-import.test.js
- packages/@lwc/jest-transformer/src/transforms/access-check-scoped-import.js
Add jest transform for `@saleforce/accessCheck/x.y` scoped modules.
Fixes [W-6356517](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007JeyCIAS/view)
> feat: add accessCheck transform

- package.json
- packages/@lwc/jest-preset/package.json
- packages/@lwc/jest-transformer/package.json
- packages/@lwc/jest-transformer/src/transforms/utils.js
@lwc/errors is a public-private (?) package
> build: remove @lwc/errors dependency

- .eslintignore
- .eslintrc
- package.json
- packages/@lwc/jest-preset/src/stubs/__tests__/auraStorageStub.test.js
- packages/@lwc/jest-preset/src/stubs/__tests__/auraStub.test.js
- packages/@lwc/jest-serializer/package.json
- packages/@lwc/jest-transformer/package.json
- packages/@lwc/jest-transformer/src/transforms/__tests__/utils/test-transform.js
- packages/wdio-lwc-service/scripts/build-test.js
- packages/wdio-lwc-service/scripts/patch-query-selector.js
- yarn.lock
Also removes wdio dependency and configuration from the root workspace.
> build: upgrade dependencies

- packages/@lwc/jest-preset/jest-preset.js
- packages/@lwc/jest-transformer/package.json
- packages/@lwc/jest-transformer/src/index.js
- yarn.lock
> feat: add TypeScript support for LWC OSS

- packages/@lwc/jest-transformer/src/index.js
This addresses issue #66 
Added source maps to Typescript step, and passed them to LWC Compiler.
> Typescript sourcemaps

- .prettierrc
- package.json
- packages/@lwc/jest-serializer/package.json
- packages/@lwc/jest-transformer/package.json
- yarn.lock
**dependencies**
@lwc/jest-serializer
```
pretty-format@25.4.0
```
@lwc/jest-transformer
```
@babel/core@7.9.0, @babel/plugin-transform-modules-commonjs@7.9.0, 
@babel/preset-typescript@7.9.0, babel-preset-jest@25.4.0
```
**devDependencies**
```
@types/jest@25.2.1, jest@25.4.0, lerna@3.20.2, prettier@2.0.4
```
> chore: update dependencies

- package.json
- yarn.lock
> chore: prepare for summer20 release

- lerna.json
- packages/@lwc/jest-preset/package.json
- packages/@lwc/jest-resolver/package.json
- packages/@lwc/jest-serializer/package.json
- packages/@lwc/jest-transformer/package.json
Release notes draft https://github.com/salesforce/lwc-test/releases/tag/untagged-bb7d206f902f4e762b1c
> v4.5.2-226.0

- packages/@lwc/jest-transformer/src/index.js
- packages/@lwc/jest-transformer/src/transforms/__tests__/site-scoped-import.test.js
- packages/@lwc/jest-transformer/src/transforms/site-scoped-import.js
add import test for @salesforce/site/Id in lwc-jest-transformer
> feat: add site scoped import test

- yarn.lock
> chore: lock file update

- packages/@lwc/jest-preset/README.md
- packages/@lwc/jest-preset/src/setup.js
- packages/@lwc/jest-transformer/src/index.js
- packages/@lwc/jest-transformer/src/transforms/__tests__/site-scoped-import.test.js
- packages/@lwc/jest-transformer/src/transforms/site-scoped-import.js
- test/src/modules/smoke/shadow/__tests__/shadow.spec.js
Adding the `site/activeLanguages` scoped module.
Awaits the corresponding PRs to lwc repos.
✅   **Request**: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000N2vsYAC/view
✅   **Spec**: https://salesforce.quip.com/BMFFAT0LMxks
> feat: add site/activeLanguages scoped module (@W-7088752)

- packages/@lwc/jest-transformer/src/transforms/__tests__/komaci-scoped-import.test.js
- packages/@lwc/jest-transformer/src/transforms/komaci-scoped-import.js
just following the instructions from https://github.com/salesforce/lwc-salesforce
> chore: add transformer for @salesforce/komaci

- packages/@lwc/jest-transformer/src/index.js
- test/src/modules/smoke/typescript/__tests__/__snapshots__/typescript.test.ts.snap
- test/src/modules/smoke/typescript/__tests__/typescript.test.ts
- test/src/modules/smoke/typescript/typescript.html
- test/src/modules/smoke/typescript/typescript.ts
> fix: allow class declarations from TS->JS

- packages/@lwc/jest-transformer/src/transforms/__tests__/site-scoped-import.test.js
- packages/@lwc/jest-transformer/src/transforms/site-scoped-import.js
Same as #180, but with just the non-stylistic changes.
@Fatema-Saifee Could you please take a look at this PR and +1?
If you'd like to make the stylistic changes, we can do them in a separate PR, ideally with ESLint/Prettier so that the styling is applied automatically.
> feat: add new salesforce site scoped module for default language (@W-12984619)

- test/src/modules/resolver/manualStylesheets/__tests__/manualStylesheets.test.js
We switched this from an error to a warning but forgot to update the test here.
> test: ignore expected warning message

- .circleci/config.yml
- package.json
> chore: node v18.18.0

- .nucleus.yaml
- package.json
Pretty much as advertised. Copied from [LWC](https://github.com/salesforce/lwc/blob/2870fc339e0d710b3d29ece8cb3d3e8923f55e17/.nucleus.yaml), with a few tweaks.
> chore: add nucleus config @W-14756916

- packages/@lwc/jest-serializer/src/clean-element-styles.js
- test/src/modules/serializer/styleAttr/__tests__/__snapshots__/styleAttr.spec.js.snap
Improve whitespace handling around `:` and in `! important`.
> fix: improve normalization of style attr

- packages/@lwc/jest-preset/README.md
- packages/@lwc/jest-transformer/src/transforms/__tests__/apex-continuation-scoped-import.test.js
- packages/@lwc/jest-transformer/src/transforms/__tests__/apex-scoped-import.test.js
- packages/@lwc/jest-transformer/src/transforms/utils.js
- test/src/modules/transformer/apex/__tests__/apex.test.js
https://github.com/salesforce/lwc-test/pull/260
> @W-16845391 Revert the breaking change for jest.fn()

- packages/@lwc/jest-transformer/src/index.js
> @W-16647806 log compiler warning during jest tests

- packages/@lwc/jest-transformer/src/index.js
[v8.18.2](https://github.com/salesforce/lwc/releases/tag/v8.18.2) - adds lwc:on behind an option `enableLwcOn`.
> @ W-19123857 feat(jest-tranformer): enable lwc:on feature by default for testing
